import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/** Auto-generated from the `docs/` directory tree. Add a new `.md`
 *  under `docs/`, `docs/api/`, `docs/faq/`, or `docs/guides/` to add a
 *  page; no sidebar edits needed. */
const sidebars: SidebarsConfig = {
	mainSidebar: [
		{
			type: "autogenerated",
			dirName: ".",
		},
	],
};

export default sidebars;
